version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka:/bitnami/kafka
  
  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka
       
  kafdrop-ae-dev:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop-ae
    environment:
      - KAFKA_BROKERCONNECT=b-1.dhbshduseast1dev.7h83a2.c2.kafka.us-east-1.amazonaws.com:9092
    ports:
      - "9002:9000"
    depends_on:
      - kafka

volumes:
  kafka: